/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_edma.h"
#include "fsl_dmamux.h"
#include "fsl_common.h"
#include "fsl_sai.h"
#include "fsl_sai_edma.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA_DMA_BASEADDR DMA0
/* Associated DMAMUX device that is used for muxing of requests. */
#define DMA_DMAMUX_BASEADDR DMAMUX
/* Definition of peripheral ID */
#define I2S0_PERIPHERAL I2S0
/* Master clock source frequency used for counting the master clock divider in the Tx SetFormat type functions, not available on all devices. */
#define I2S0_TX_MCLK_SOURCE_CLOCK_HZ 120000000UL
/* Bit clock source frequency used for counting the bit clock divider in the Tx SetFormat type functions. */
#define I2S0_TX_BCLK_SOURCE_CLOCK_HZ 6144000UL
/* I2S0 eDMA source request. */
#define I2S0_TX_DMA_REQUEST kDmaRequestMux0I2S0Tx
/* Selected eDMA channel number. */
#define I2S0_TX_DMA_CHANNEL 0
/* DMAMUX device that is used for muxing of the request. */
#define I2S0_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define I2S0_TX_DMA_BASEADDR DMA0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const edma_config_t DMA_config;
extern const sai_config_t I2S0_tx_config;
extern sai_transfer_format_t I2S0_tx_format;
extern edma_handle_t I2S0_TX_Handle;
extern sai_edma_handle_t I2S0_SAI_Tx_eDMA_Handle;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
